<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class BlogPostCreateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    private $id=0;
    public function authorize()
    {
        // в будущем проверка на авторизацию пользователя
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title'=>'required|min:3|max:255|unique:blog_posts',
            'slug'=>Rule::unique('blog_posts')->ignore($this->route('post')),
            'excerpt'=>'max:500',
            'content_raw'=>'required|string|min:5|max:10000',
            // то значение которое приходит, должно быть в таблице блог_категории и поле ид
            'category_id'=>'required|integer|exists:blog_categories,id'
        ];
    }
    public function messages()
    {
        return [
            'slug.unique' => 'Такой идентификатор уже существует',
            'title.min' => [
                'numeric' => 'The :attribute must be at least :min.',
                'file' => 'The :attribute must be at least :min kilobytes.',
                'string' => 'The :attribute должен at least :min characters.',
                'array' => 'The :attribute must have at least :min items.',
            ],
            'content_raw.required' => 'Введите текст статьи.'
        ];
    }

    public function attributes()
    {
        //return parent::attributes(); // TODO: Change the autogenerated stub
        return [
            'title' =>'заголовок',
        ];
    }
}
